//CONVERSATION CONTEXT
export const NEW_CONVERSATION = 'NEW_CONVERSATION';

//CHATWINDOW EVENTS
export const SEND_MESSAGE  = 'SEND_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';


export const MARK_READ = 'MARK_READ'
export const UPDATE_UNREAD_COUNT = 'UPDATE_UNREAD_COUNT';
export const TYPING = 'TYPING';
export const STOP_TYPING = 'STOP_TYPING';
export const USER_ONLINE = 'USER_ONLINE';
export const USER_OFFLINE = 'USER_OFFLINE';
export const READ_MESSAGE = 'READ_MESSAGE';