export const NEW_CONVERSATION = 'NEW_CONVERSATION';
export const UPDATE_CONVERSATION = 'UPDATE_CONVERSATION';

export const SEND_MESSAGE  = 'SEND_MESSAGE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const JOIN_CONVERSATION = 'JOIN_CONVERSATION';
export const LEAVE_CONVERSATION = 'LEAVE_CONVERSATION'

export const MARK_READ = 'MARK_READ'
export const UPDATE_UNREAD_COUNT = 'UPDATE_UNREAD_COUNT';
export const TYPING = 'TYPING';
export const STOP_TYPING = 'STOP_TYPING';
export const USER_ONLINE = 'USER_ONLINE';
export const USER_OFFLINE = 'USER_OFFLINE';
export const READ_MESSAGE = 'READ_MESSAGE';